name: Admin Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Fetches the latest code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Set the Node.js version

      - name: install Backend dependencies
        run: npm install

      - name: navigate to frontend
        run: cd admin-portal 

      - name: install frontend dependencies
        run: npm install

      - name: Build the app
        run: npm run build  # Builds the React app
